export const TODOS_SET = 'TODOS_SET';
export type TODOS_SET = typeof TODOS_SET;

export const TODOS_SET_VISIBILTY = 'TODOS_SET_VISIBILTY';
export type TODOS_SET_VISIBILTY = typeof TODOS_SET_VISIBILTY;

// export const TODOS_VISIBILTY_FILTER = {
//     TODOS_VIEW_ALL: 'TODOS_VIEW_ALL',
//     TODOS_VIEW_CLOSED: 'TODOS_VIEW_CLOSED',
//     TODOS_VIEW_OPEN: 'TODOS_VIEW_OPEN'
// }
// export type TODOS_VISIBILTY_FILTER = typeof TODOS_VISIBILTY_FILTER;

export const TODOS_VIEW_ALL = 'TODOS_VIEW_ALL';
export type TODOS_VIEW_ALL = typeof TODOS_VIEW_ALL;

export const TODOS_VIEW_CLOSED = 'TODOS_VIEW_CLOSED';
export type TODOS_VIEW_CLOSED = typeof TODOS_VIEW_CLOSED;

export const TODOS_VIEW_OPEN = 'TODOS_VIEW_OPEN';
export type TODOS_VIEW_OPEN = typeof TODOS_VIEW_OPEN;